language: haxe
haxe: 4.0.5
hxml:
  - unittests.hxml
  - package.hxml
  - doc.hxml

before_install:
  - curl -s "https://get.sdkman.io" | bash
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - sdk install java 8.0.232.j9-adpt
  - sdk install maven 3.6.3
  - cp stuff/settings.xml ~/.m2/settings.xml
  - sed -i "s/__USER__/${mvn_user}/g" ~/.m2/settings.xml
  - sed -i "s/__PASSWORD__/${mvn_password}/g" ~/.m2/settings.xml

before_script:
  - "./stuff/java_clone.sh"

after_script:
  - "./stuff/java_commit.sh"

deploy:
  provider: pages
  local_dir: doc
  github_token: "$doc_token"
  skip_cleanup: true
  keep_history: false
  on:
    branch: master

after_deploy:
  - export GPG_TTY=$(tty)
  - openssl aes-256-cbc -K $encrypted_6c315054a92d_key -iv $encrypted_6c315054a92d_iv -in stuff/key.gpg.enc -out stuff/key.gpg -d
  - gpg --batch --passphrase ${mvn_passphrase} --import stuff/key.gpg
  - rm stuff/key.gpg
  - mvn gpg:sign-and-deploy-file
    -DpomFile=stuff/pom.xml
    -Dfile=_build/java/Packager.jar
    -Durl=https://oss.sonatype.org/service/local/staging/deploy/maven2/
    -DrepositoryId=maven-central
    -Dgpg.passphrase=${mvn_passphrase}
