language: haxe
haxe: 4.0.5
hxml:
  - unittests.hxml
  - package.hxml
  - doc.hxml

before_install:
  - export sdk_version=$(cat VERSION)
  - echo "SDK Version is $sdk_version."
  - curl -s "https://get.sdkman.io" | bash
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - sdk install java 8.0.232.j9-adpt

before_script:
  - "./stuff/java_clone.sh"

after_script:
  - "./stuff/java_commit.sh"

deploy:
  provider: pages
  local_dir: doc
  github_token: "$doc_token"
  skip_cleanup: true
  keep_history: false
  on:
    branch: CUSDK-57-npm-deployment

after_deploy:
# Deploy to Maven Central
  - echo "*** Deploying to Maven Central..."
  - openssl aes-256-cbc -K $encrypted_6c315054a92d_key -iv $encrypted_6c315054a92d_iv -in stuff/key.gpg.enc -out stuff/key.gpg -d
  #- openssl aes-256-cbc -K $encrypted_4ac79ed20675_key -iv $encrypted_4ac79ed20675_iv -in stuff/key2.gpg.enc -out stuff/key.gpg -d
  - gpg --batch --passphrase ${mvn_passphrase} --import stuff/key.gpg
  - rm stuff/key.gpg
  - python3 stuff/deploy_maven_central.py
# Deploy to npm
  - "*** Deploying to npm..."
  - cp stuff/npmrc ~/.npmrc
  - sed -i "s/__TOKEN__/${npm_token}/g" ~/.npmrc
  - sed -i "s/__VERSION__/${npm_token}/g" stuff/package.json
  - cd _build/js
  - npm publish
  - cd ../..
# Deploy to PyPI
  - echo "*** Deploying to PyPI..."
  - sudo apt install python3-pip -y
  - sudo -H pip3 install --upgrade pip
  - sudo -H pip3 install wheel
  - sudo -H pip3 install twine
  - cd _build/python
  - python3 setup.py sdist bdist_wheel
  - twine upload -u __token__ -p $pypi_token dist/*
  - cd ../..
