language: haxe
haxe: "4.0.5"
hxml:
  - unittests.hxml
  - package.hxml
  - doc.hxml

after_success:
  - mvn deploy:deploy-file -Dregistry=https://maven.pkg.github.com/JaviCerveraIngram -Dtoken=$doc_token -DpomFile=stuff/pom.xml -Dfile=_build/java/Packager.jar

deploy:
  provider: pages
  local_dir: doc
  github_token: $doc_token
  skip_cleanup: true
  keep_history: false
  on:
    branch: master
