language: haxe
haxe: "4.0.5"
hxml:
  - unittests.hxml
  - package.hxml
  - doc.hxml

before_install:
#  - sudo apt install openjdk-8-jdk -y
#  - sudo update-java-alternatives --set java-1.8.0-openjdk-amd64
#  - sudo apt install maven -y
  - curl -s "https://get.sdkman.io" | bash
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - sdk install java 8.0.232.j9-adpt
  - sdk install maven 3.6.3
  - cp stuff/settings.xml ~/.m2/settings.xml
  - sed -i "s/__TOKEN__/${mvn_token}/g" ~/.m2/settings.xml

before_script:
  - ./stuff/before_script.sh

after_script:
  - ./stuff/after_script.sh

deploy:
  provider: pages
  local_dir: doc
  github_token: $doc_token
  skip_cleanup: true
  keep_history: false
  on:
    branch: master

after_deploy:
  - mvn deploy:deploy-file -Dregistry=https://maven.pkg.github.com/JaviCerveraIngram -Dtoken=$mvn_token -DrepositoryId=github -Durl=https://maven.pkg.github.com/JaviCerveraIngram/connect-haxe-sdk -DpomFile=stuff/pom.xml -Dfile=_build/java/Packager.jar
