language: haxe
haxe: "4.0.5"
hxml:
  - unittests.hxml
  - package.hxml
  - doc.hxml

before_install:
  - javac -version
  - sudo apt install openjdk-8-jdk -y
  - update-java-alternatives --list
#  - curl -s "https://get.sdkman.io" | bash
#  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
#  - sdk install java 8.0.232.j9-adpt
  - javac -version

after_success:
  - mvn deploy:deploy-file -Dregistry=https://maven.pkg.github.com/JaviCerveraIngram -Dtoken=$doc_token -DpomFile=stuff/pom.xml -Dfile=_build/java/Packager.jar

deploy:
  provider: pages
  local_dir: doc
  github_token: $doc_token
  skip_cleanup: true
  keep_history: false
  on:
    branch: master
